env:
  global:
    - secure: ZzgE9z+oFeTQOT+CTRbeOkADomsT79bSJK3w3s+POtGbIhd75Nau/bFlB1xYRKwiUSckI1ZoDut3yulNfxbcHcnXgz3aBo/i/R6Q9T72lhHFQ5p70jWRVyHOK8d793uixK05gz3Z1xhbkBPivw2dyqLD2qAFYvdPmGedsfdkhTbE6VNxVIJbSx2vcYdp3lY4qSo8loiysWkS7/1rFhwPiFo9oVcQz58Gyg9tCqIRLJ5dpRp5+OQbDmh/ZJfTaDviS4GFLoILmkUaUFIAYSd1Unzb5F8XlsEpFmKw4GxefuN8VQYOlHGDWV/aGBL0CL1gaufCdGdZhI0Gl8NJBDMlfEDbcxkYSveARsfMG1mRaLCfY+6fD80npwtk7p5Bt0+5y3Qc1B+NQZ24Il9P7PT2fyix/nRF3FG6U5hyVSjnLllAiA9rYewB98CgxcQndng+cGLxB+CfbPTmlJelVqcLHrI2ljqTWwYMRezsviG1bUgtzH7sBZs1UzzYtvVZg6aPq2350pRWgboolLkSFOVH4bffBEJgKQ9l4ZC+tFeSJmsDIC/3ksKPLd9uxC6ulNLlhpgTIdeu79tke1hsrr3Q3CpGgGHdfDxLxOPQRPgt54LD84PQWvF+O8OFLAuY3qyBm9j9l2bFAMwRGOiF+wYoLDkxKFJCCQDnD4JLtOvwFx8=
    - secure: sGtlQCyli6FBnZuv+wXzPTOhEHXkeDlc9tTyfrDRnN+RP0WiP7B1rAxzXe3A8A2B5K3Wx5msxh5xnIvhvrCkvvHIbmz8OzIURsxnbLd0yfnGTAWiewHm/tmjwm3cteXIBXL7ABYCcOubDK2/A6kKSoBI6RL/t9qVTNtI3InEssr8kMvqZJ8iK5NOWep4okPJlNgt44/moetK3CxwR7Z1vH4EJYmvUBJTaWd+wKsVjh43yHICSTYNnsp26vt/rs9ayp8pFG8qx4HONn0VhS1JPtAJwEw1TD8Jx+EpuEOhf/9iHFCpLuHRFpnKalNUyHxAEbr+pSMSwP9ZANKy6svSAp9OqTOjVMOpfXYnwWPkYz6QcYxoE4AizGVqpa3YTFwMtwj7MQEzFsrOJ56x53/TCGaChBy1X9+fXC6pThOlBDuWSsRCNiVEZQElwzE9p+8cIK6x5MzysaX7vlkD/2byKwJAX3WsKB6VV6ZoH580sDKB6fm99TH2FyQbs7vcP3nxoi46YBnbvMOooDCeN9oufFVqfb8Evgc6J8JECZN64PlANnsoOSqzvTUWjPvEZu5kdCf/75Jp6ko5h+iHKyv2DKLt2j93n5TEoWe99puUO4oKLEatgY+RhFS6EIX4Uv/e9W21eR/13xEFe66SjPbOdyDFHF8oixM4hYKKJI7avPM=

language: python

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.40.3/hugo_0.40.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - pip install Pygments
  
script:
  - hugo

after_success:
  - curl --ftp-create-dirs -T public sftp://${SFTP_USER}:${SFTP_PASSWORD}@biocozy.net/biocozy.net/blog
